apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-marketing-frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: digital-marketing-frontend-deployment
  template:
    metadata:
      labels:
        app: digital-marketing-frontend-deployment
    spec:
      containers:
        - name: digital-marketing-frontend
          image: elghibaomar/digital-marketing-frontend:latest
          env:
            - name: PORT
              value: "8082"
          ports:
          - containerPort: 8082


---
apiVersion: v1
kind: Service
metadata:
  name: digital-marketing-frontend-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
  selector:
    app: digital-marketing-frontend-deployment






