apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs-k8s-web-final-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vuejs-k8s-web-final-deployment
  template:
    metadata:
      labels:
        app: vuejs-k8s-web-final-deployment
    spec:
      containers:
        - name: vuejs-k8s-web-final
          image: elghibaomar/vuejs-k8s-web-final:latest
          env:
            - name: PORT
              value: "8080"
          ports:
          - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: vuejs-k8s-web-final-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: vuejs-k8s-web-final-deployment