# Generated by Django 4.0.5 on 2022-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_Marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='Countries',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='Marital',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='Product_id',
            field=models.CharField(max_length=50),
        ),
    ]
