name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: QuioBot/QuioBot_DigitalMarketing_Api/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      CLUSTER_NAME: project-k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Insall doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to DO Container Registry with short-lived creds
        run: doctl registry login --expiry-seconds 1200
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - name: Build container image
        working-directory: .
        run: |
          docker build -f Dockerfile \
            -t elghibaomar/digital-marketing-api:latest \
            -t elghibaomar/digital-marketing-api:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .

      - name: Push image
        run: |
          docker push elghibaomar/digital-marketing-api --all-tags
      - name: K8s cluster kubeconfig file with/ short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update deployment secrets
        run: |
          cat << EOF >> .env.prod
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          EOF
          kubectl delete secret digital-marketing-api-prod-env
          kubectl create secret generic digital-marketing-api-prod-env --from-env-file=.env.prod
      - name: Update Deployment image
        run: |
          kubectl set image deployment/digital-marketing-api-deployment digital-marketing-api=elghibaomar/digital-marketing-api:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/digital-marketing-api-deployment
      - name: Post-build Django Commands - Migrate / Collectstatic
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=digital-marketing-api-deployment -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/collectstatic.sh





